name: Setup Ollama and Open WebUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://ollama.com/install.sh | sh
          pip install open-webui

      - name: Download and Start Models
        run: |
          models=(
            "qwen2.5:32b"
          )

          for model in "${models[@]}"; do
            ollama pull "$model"
            ollama run "$model" &
          done

      - name: Start Open WebUI Server
        run: |
          from open_webui import serve

          # Load your custom settings here
          custom_settings = {
              # 'setting_key': 'setting_value',
          }

          serve(settings=custom_settings)
